<?php

namespace contactBoxBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\HttpFoundation\Request;

use contactBoxBundle\Entity\Person;
use contactBoxBundle\Entity\Address;
use contactBoxBundle\Entity\Phone;
use contactBoxBundle\Entity\Email;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository
{

    public function getPersonByAddresId($id){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT p FROM contactBoxBundle:Person p WHERE p.address.id :start");
        $query->setParameter("start", $id);
        
        $person = $query->getResult();
        return $person; 
    }

    
    public function getPersonByEmailId($id){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT p , e FROM contactBoxBundle:Person p WHERE p.address : :start");
        $query->setParameter("start", $id);
        
        $person = $query->getResult();
        return $person;         
    }

    public function getPersonByPhoneId($id){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT p FROM contactBoxBundle:Person p WHERE p.phone_id :start");
        $query->setParameter("start", $id);
        
        $person = $query->getResult();
        return $person;        
    }
    
}
